// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WatchitWebApp.Entities;

namespace WatchitWebApp.Migrations
{
    [DbContext(typeof(WatchitDBContext))]
    [Migration("20240728102217_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WatchitWebApp.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 7, 28, 13, 22, 6, 373, DateTimeKind.Local).AddTicks(8622),
                            Email = "m@gmail.com",
                            IsVerified = true,
                            Login = "zera",
                            Name = "Max",
                            Password = "$MYHASH$V1$10000$MJkIJsIXH9WSHKBHTJitfKj88gqyIhuf+Ud++2m8ivlelC2n",
                            Username = "zeratul"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 7, 28, 13, 22, 6, 379, DateTimeKind.Local).AddTicks(9526),
                            Email = "egor@gmail.com",
                            IsVerified = false,
                            Login = "egazan11",
                            Name = "Egor",
                            Password = "$MYHASH$V1$10000$4BMNnYEdVkJCHb5vVv3mu35WrJosLuMySfHK/WCTOvea2gzT",
                            Username = "agoa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
